
import algorithm, future, strutils, unicode, tables

iterator permutations*(text: string): string =
  # Adapted from https://bitbucket.org/nimcontrib/nimcombinatorics/src/4b61d417e9ad4386caf3791f1999fd9889193e01/combinatorics.nim?at=default&fileviewer=file-view-default
  # Credit/licence at end of file
  # Iterates through all possible combinations of the letters in text
  let n = len(text)
  var position = newSeq[int](n)
  var newPermutation = newString(n)
  for i in 0..<n:
    position[i] = i
  while true:
    for i in 0..<n:
      newPermutation[i] = newPermutation[position[i]]
      newPermutation[position[i]] = text[i]
    yield newPermutation
    var i = 1
    while i < n:
      position[i] -= 1
      if position[i] < 0:
        position[i] = i
        i += 1
      else:
        break
    if i >= n:
      break

proc isAnagram*(word, scrambledWord: string): bool =
  # Returns true if scrabledWord is an anagram of word
  if len(scrambledWord) == len(word):
    var 
      wordCharacters = lc[x | (x <- word), char] 
      scrambledCharacters = lc[x | (x <- scrambledWord), char]  
    sort(wordCharacters, system.cmp[char])
    sort(scrambledCharacters, system.cmp[char])
    if wordCharacters == scrambledCharacters:
      return true
  return false

iterator stepBy*(text: string; stepSize: int, startPoint: int = 0, endPoint: int = text.high): string =
  # Step through letters with a given interval, start and end point
  var 
    endPosition = text.high
    startPosition = 0
  if endPoint <= text.high and endPoint >= 0:
      endPosition = endPoint
  if startPoint <= text.high and startPoint >= 0:
      startPosition = startPoint
  var
    characters = lc[x | (x <- text), char]
    stepped = ""
    lastPosition = stepSize * -1 + startPosition
  for i in startPosition..endPosition:
    if i == lastPosition + stepSize:
      lastPosition += stepSize
      stepped &= characters[i]
  yield stepped

proc removeVowels*(text: string): string =
  # In case you are a musician like MGMT or SBTRKT and really hate vowels...
  result = split(text, {'a','e','i', 'o', 'u'}).join("")

proc countVowels*(text: string): int =
  # Just to make sure none of those pesky vowels sneak in to your stage name
  result = 0
  for i in text:
    if i in ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']:
      inc result

proc countConstonants*(text: string): int =
  result = len(text)
  result -= countVowels(text)

proc mostCommonLetter*(text: string): char =
  var counts = initCountTable[char]()
  for letter in text:
    if counts.contains(letter):
      inc counts[letter]
    else:
      counts[letter] = 1
  result = largest(counts).key

proc isPallindrome*(text: string): bool =
  if text == reversed(text):
    return true
  else:
    return false

proc isPangram*(text: string): bool =
  # Returns true if the text contains every letter in the English alphabet (a pangram)
  let pangram = strutils.toLower(text)
  var count = 0
  for letter in 'a'..'z':
      if letter in pangram:
        inc count
  if count == 26:
      return true
  else:
      return false

proc makeAcronym*(text: string): string =
  # Makes an acronym from a string containing whitespace separated words
  var words = split(text)
  result = ""
  for word in words:
    result &= word[0]


# Credit for permutations iterator:

#[Copyright (c) 2014 Reimer Behrends

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.]#
